import Foundation

public struct AgentHookInstallResult: Sendable, Equatable {
    public let writtenFiles: [URL]

    public init(writtenFiles: [URL]) {
        self.writtenFiles = writtenFiles
    }
}

public struct AgentHookInstaller: Sendable {
    public static let version = "1"

    public let rootDirectory: URL
    public let grafttyCLIPath: String

    public init(rootDirectory: URL, grafttyCLIPath: String) {
        self.rootDirectory = rootDirectory
        self.grafttyCLIPath = grafttyCLIPath
    }

    public static func rootDirectory(defaultDirectory: URL = AppState.defaultDirectory) -> URL {
        defaultDirectory.appendingPathComponent("agent-hooks", isDirectory: true)
    }

    public static func binDirectory(rootDirectory: URL) -> URL {
        rootDirectory.appendingPathComponent("bin", isDirectory: true)
    }

    public var binDirectory: URL {
        Self.binDirectory(rootDirectory: rootDirectory)
    }

    public static func zshInitDirectory(rootDirectory: URL) -> URL {
        rootDirectory.appendingPathComponent("zsh-init", isDirectory: true)
    }

    public var zshInitDirectory: URL {
        Self.zshInitDirectory(rootDirectory: rootDirectory)
    }

    public func install() throws -> AgentHookInstallResult {
        try FileManager.default.createDirectory(at: binDirectory, withIntermediateDirectories: true)

        var written: [URL] = []
        let claudeWrapper = binDirectory.appendingPathComponent("claude")
        let codexWrapper = binDirectory.appendingPathComponent("codex")
        let codexHomeDirectory = binDirectory
            .deletingLastPathComponent()
            .appendingPathComponent("codex-home", isDirectory: true)
            .path

        try writeIfChanged(
            AgentHookInstaller.wrapperScript(
                runtime: .claude,
                wrapperDirectory: binDirectory.path,
                realCommandName: "claude",
                grafttyCLIPath: grafttyCLIPath,
                codexHomeDirectory: codexHomeDirectory
            ),
            to: claudeWrapper,
            executable: true,
            written: &written
        )
        try writeIfChanged(
            AgentHookInstaller.wrapperScript(
                runtime: .codex,
                wrapperDirectory: binDirectory.path,
                realCommandName: "codex",
                grafttyCLIPath: grafttyCLIPath,
                codexHomeDirectory: codexHomeDirectory
            ),
            to: codexWrapper,
            executable: true,
            written: &written
        )

        try installZshInitShim(written: &written)

        return AgentHookInstallResult(writtenFiles: written)
    }

    /// Writes the ZDOTDIR shim files (`.zshenv`, `.zprofile`, `.zshrc`,
    /// `.zlogin`) under `zshInitDirectory`. Surface launches set
    /// `ZDOTDIR` to that path so zsh reads our `.zshrc` instead of the
    /// home one. Our `.zshrc` sources the user's real `.zshrc` first, then
    /// re-prepends the wrapper bin to PATH — defending against user
    /// shell-init `export PATH="<dir>:$PATH"` lines that would otherwise
    /// push graftty's bin behind `~/.bun/bin`, `~/.local/bin`, etc.,
    /// causing `claude` / `codex` to resolve to the unwrapped binaries.
    private func installZshInitShim(written: inout [URL]) throws {
        try FileManager.default.createDirectory(at: zshInitDirectory, withIntermediateDirectories: true)

        // .zshenv / .zprofile / .zlogin: zsh skips home versions when
        // ZDOTDIR is set, so the shim files have to source them
        // explicitly to preserve user behavior.
        for (basename, homeBasename) in [
            (".zshenv", ".zshenv"),
            (".zprofile", ".zprofile"),
            (".zlogin", ".zlogin"),
        ] {
            try writeIfChanged(
                Self.zshSourceShim(homeBasename: homeBasename),
                to: zshInitDirectory.appendingPathComponent(basename),
                executable: false,
                written: &written
            )
        }

        // .zshrc: source user's real .zshrc, then re-prepend our wrapper
        // bin (idempotent under nested zsh).
        try writeIfChanged(
            Self.zshrcShim(),
            to: zshInitDirectory.appendingPathComponent(".zshrc"),
            executable: false,
            written: &written
        )
    }

    static func zshSourceShim(homeBasename: String) -> String {
        """
        # Generated by graftty AgentHookInstaller. Sourced by zsh because
        # `ZDOTDIR` points at the graftty agent-hooks zsh-init directory,
        # which causes zsh to skip the user's home equivalent. Source it
        # explicitly so user behavior is preserved.
        [ -r "$HOME/\(homeBasename)" ] && source "$HOME/\(homeBasename)"
        """
    }

    static func zshrcShim() -> String {
        """
        # Generated by graftty AgentHookInstaller. Source the user's real
        # .zshrc first so any user PATH manipulations run; then re-prepend
        # graftty's wrapper bin so `claude` / `codex` resolve to our
        # wrapper rather than the upstream installations in
        # `~/.bun/bin` / `~/.local/bin` / etc.
        [ -r "$HOME/.zshrc" ] && source "$HOME/.zshrc"

        if [ -n "$GRAFTTY_AGENT_HOOKS_BIN" ]; then
            # Strip any existing occurrences of our bin so nested zsh
            # invocations don't accumulate duplicates.
            case ":$PATH:" in
                *":$GRAFTTY_AGENT_HOOKS_BIN:"*)
                    local _graftty_path=":$PATH:"
                    _graftty_path="${_graftty_path//:$GRAFTTY_AGENT_HOOKS_BIN:/:}"
                    _graftty_path="${_graftty_path#:}"
                    _graftty_path="${_graftty_path%:}"
                    PATH="$_graftty_path"
                    unset _graftty_path
                    ;;
            esac
            export PATH="$GRAFTTY_AGENT_HOOKS_BIN:$PATH"
        fi
        """
    }

    public static func wrapperScript(
        runtime: TeamHookRuntime,
        wrapperDirectory: String,
        realCommandName: String,
        grafttyCLIPath: String,
        codexHomeDirectory: String
    ) -> String {
        let resolveBlock = realBinaryResolutionShell(
            wrapperDirectory: wrapperDirectory,
            realCommandName: realCommandName
        )
        let trapBlock = """
        cleanup() { \(shellCommandToken(grafttyCLIPath)) team unregister --runtime \(runtime.rawValue) 2>/dev/null || true; }
        trap cleanup EXIT
        """

        let runtimeBlock: String
        switch runtime {
        case .claude:
            let inlineJSON = claudeInlineSettingsJSON(grafttyCLIPath: grafttyCLIPath)
            let escapedJSON = shellLiteral(inlineJSON)
            runtimeBlock = """
            if [ "${GRAFTTY_DISABLE_AGENT_HOOKS:-}" != "1" ]; then
              ( exec "$real_binary" --settings \(escapedJSON) "$@" )
            else
              ( exec "$real_binary" "$@" )
            fi
            """
        case .codex:
            let codexHomeLiteral = shellLiteral(codexHomeDirectory)
            runtimeBlock = """
            if [ "${GRAFTTY_DISABLE_AGENT_HOOKS:-}" != "1" ]; then
              \(shellCommandToken(grafttyCLIPath)) internal sync-codex-home
              ( exec env CODEX_HOME=\(codexHomeLiteral) "$real_binary" "$@" )
            else
              ( exec "$real_binary" "$@" )
            fi
            """
        }

        return """
        #!/bin/sh
        # GRAFTTY_AGENT_HOOK_WRAPPER version=\(version)
        # Hooks run: \(grafttyCLIPath) team hook \(runtime.rawValue)
        \(resolveBlock)

        \(trapBlock)

        \(runtimeBlock)
        exit $?
        """
    }

    /// @spec TEAM-IDLE-1.2
    /// Builds the inline `--settings` JSON payload that the Claude wrapper
    /// passes to `claude --settings '<json>'`. Lays the graftty hooks
    /// additively over the user's existing settings.
    private static func claudeInlineSettingsJSON(grafttyCLIPath: String) -> String {
        let cmd = grafttyCLIPath
        var hooks: [String: Any] = [:]
        for event in TeamHookEvent.allCases {
            if event == .stop {
                hooks[event.camelCaseKey] = [
                    [
                        "hooks": [
                            ["type": "command", "command": "\(cmd) team hook claude \(event.rawValue)"],
                            [
                                "type": "command",
                                "command": "\(cmd) team watch-inbox claude",
                                "async": true,
                                "asyncRewake": true,
                                "timeout": 86400,
                            ],
                        ],
                    ],
                ]
            } else {
                hooks[event.camelCaseKey] = hookEntries(command: "\(cmd) team hook claude \(event.rawValue)")
            }
        }
        let payload: [String: Any] = ["hooks": hooks]
        // Note: .sortedKeys produces alphabetical event order (PostToolUse, SessionStart, Stop).
        // JSON object key order has no semantic effect; sorting just keeps the wrapper output stable.
        let data = (try? JSONSerialization.data(
            withJSONObject: payload,
            options: [.sortedKeys, .withoutEscapingSlashes]
        )) ?? Data("{}".utf8)
        return String(data: data, encoding: .utf8) ?? "{}"
    }

    private static func realBinaryResolutionShell(wrapperDirectory: String, realCommandName: String) -> String {
        """
        real_binary=""
        old_ifs="$IFS"
        IFS=":"
        for dir in $PATH; do
          if [ "$dir" = \(shellLiteral(wrapperDirectory)) ]; then
            continue
          fi
          if [ -x "$dir/\(realCommandName)" ]; then
            real_binary="$dir/\(realCommandName)"
            break
          fi
        done
        IFS="$old_ifs"

        if [ -z "$real_binary" ]; then
          printf '%s\\n' "graftty: unable to find real \(realCommandName) outside \(wrapperDirectory)" >&2
          exit 127
        fi
        """
    }

    private static func hookEntries(command: String) -> [[String: Any]] {
        [
            [
                "hooks": [
                    [
                        "type": "command",
                        "command": command,
                    ],
                ],
            ],
        ]
    }

    private func writeIfChanged(
        _ string: String,
        to url: URL,
        executable: Bool,
        written: inout [URL]
    ) throws {
        try writeIfChanged(Data(string.utf8), to: url, executable: executable, written: &written)
    }

    private func writeIfChanged(
        _ data: Data,
        to url: URL,
        executable: Bool,
        written: inout [URL]
    ) throws {
        let existing = try? Data(contentsOf: url)
        guard existing != data else {
            if executable {
                try makeExecutable(url)
            }
            return
        }
        try FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try data.write(to: url, options: .atomic)
        if executable {
            try makeExecutable(url)
        }
        written.append(url)
    }

    private func makeExecutable(_ url: URL) throws {
        try FileManager.default.setAttributes(
            [.posixPermissions: NSNumber(value: Int16(0o755))],
            ofItemAtPath: url.path
        )
    }

    private static func shellCommandToken(_ value: String) -> String {
        guard value.rangeOfCharacter(from: .whitespacesAndNewlines) != nil ||
              value.contains("'") ||
              value.contains("\"")
        else {
            return value
        }
        return shellLiteral(value)
    }

    private static func shellLiteral(_ value: String) -> String {
        "'" + value.replacingOccurrences(of: "'", with: "'\"'\"'") + "'"
    }
}
