import Foundation
#if canImport(Darwin)
import Darwin
#elseif canImport(Glibc)
import Glibc
#endif

/// @spec TEAM-IDLE-1.1: When Graftty synthesizes a managed CODEX_HOME, the application shall union the user's Codex hooks with Graftty's current SessionStart hook and remove stale Graftty delivery hooks.
/// Synthesizes a CODEX_HOME directory that mirrors the user's `~/.codex/`
/// via symlinks, with `hooks.json` and the managed `config.toml` snapshot
/// generated by Graftty. Configuration mutations run against the durable home;
/// the wrapper enables hooks with a launch-scoped CLI override. Idempotent -
/// runs via `graftty internal sync-codex-home` before managed sessions.
public struct CodexHomeMirror: Sendable {
    public static let grafttyCommandPrefix = "graftty team hook codex"

    public let sourceDirectory: URL
    public let mirrorDirectory: URL
    public let grafttyCLIPath: String

    public init(sourceDirectory: URL, mirrorDirectory: URL, grafttyCLIPath: String) {
        self.sourceDirectory = sourceDirectory
        self.mirrorDirectory = mirrorDirectory
        self.grafttyCLIPath = grafttyCLIPath
    }

    /// `<rootDirectory>/codex-home/` where rootDirectory = AgentHookInstaller's root.
    public static func defaultMirrorDirectory(rootDirectory: URL = AgentHookInstaller.rootDirectory()) -> URL {
        rootDirectory.appendingPathComponent("codex-home", isDirectory: true)
    }

    public static func defaultSourceDirectory() -> URL {
        URL(fileURLWithPath: NSHomeDirectory())
            .appendingPathComponent(".codex", isDirectory: true)
    }

    /// Strip-and-rewrite. Idempotent.
    public func rebuild() throws {
        let fm = FileManager.default
        try fm.createDirectory(at: mirrorDirectory, withIntermediateDirectories: true)
        let lockFD = try acquireRebuildLock()
        defer {
            #if canImport(Darwin)
            _ = Darwin.lockf(lockFD, F_ULOCK, 0)
            _ = Darwin.close(lockFD)
            #elseif canImport(Glibc)
            _ = Glibc.lockf(lockFD, F_ULOCK, 0)
            _ = Glibc.close(lockFD)
            #endif
        }
        try fm.createDirectory(at: sourceDirectory, withIntermediateDirectories: true)

        try migrateLegacyConfigIfNeeded()

        let sourceEntries: [String] = (try? fm.contentsOfDirectory(atPath: sourceDirectory.path)) ?? []
        let owned: Set<String> = [
            "hooks.json",
            "config.toml",
            ".graftty-mirror-version",
            ".graftty-mirror.lock",
        ]
        let mirroredEntries = sourceEntries.filter { !owned.contains($0) }

        // Pass 1: write/refresh symlinks for every durable source entry.
        for name in mirroredEntries {
            let linkPath = mirrorDirectory.appendingPathComponent(name)
            let target = sourceDirectory.appendingPathComponent(name)
            try replaceSymlink(at: linkPath, target: target)
        }

        // Pass 2: prune mirror entries that no longer belong to the durable
        // source, excluding Graftty's generated files.
        let mirrorEntries: [String] = (try? fm.contentsOfDirectory(atPath: mirrorDirectory.path)) ?? []
        let mirroredSet = Set(mirroredEntries)
        for name in mirrorEntries where !owned.contains(name) && !mirroredSet.contains(name) {
            try? fm.removeItem(at: mirrorDirectory.appendingPathComponent(name))
        }

        // Pass 3: write Graftty-owned files.
        try writeManagedConfig()
        try writeMergedHooks()
        try "2\n".write(
            to: mirrorDirectory.appendingPathComponent(".graftty-mirror-version"),
            atomically: true,
            encoding: .utf8
        )
    }

    private func replaceSymlink(at link: URL, target: URL) throws {
        let fm = FileManager.default
        // Existing symlink to the same target — keep as-is (idempotent).
        if let existing = try? fm.destinationOfSymbolicLink(atPath: link.path),
           existing == target.path {
            return
        }
        try? fm.removeItem(at: link)
        do {
            try fm.createSymbolicLink(atPath: link.path, withDestinationPath: target.path)
        } catch {
            if let existing = try? fm.destinationOfSymbolicLink(atPath: link.path),
               existing == target.path {
                return
            }
            throw error
        }
    }

    private func writeMergedHooks() throws {
        let userHooksURL = sourceDirectory.appendingPathComponent("hooks.json")
        var root: [String: Any] = [:]
        if let data = try? Data(contentsOf: userHooksURL),
           let parsed = try? JSONSerialization.jsonObject(with: data) as? [String: Any] {
            root = parsed
        }
        var hooks = (root["hooks"] as? [String: Any]) ?? [:]
        for event in TeamHookEvent.allCases {
            let key = event.camelCaseKey
            let existing = (hooks[key] as? [[String: Any]]) ?? []
            let stripped = existing.filter { group in
                let handlers = (group["hooks"] as? [[String: Any]]) ?? []
                return !handlers.contains(where: { handler in
                    guard let command = handler["command"] as? String else { return false }
                    return Self.isGrafttyCodexHookCommand(command)
                })
            }
            hooks[key] = event == .sessionStart
                ? stripped + [grafttyMatcherGroup(event: event)]
                : stripped
        }
        root["hooks"] = hooks

        let outURL = mirrorDirectory.appendingPathComponent("hooks.json")
        let data = try JSONSerialization.data(withJSONObject: root, options: [.prettyPrinted, .sortedKeys])
        try data.write(to: outURL, options: .atomic)
    }

    private func grafttyMatcherGroup(event: TeamHookEvent) -> [String: Any] {
        [
            "hooks": [
                [
                    "type": "command",
                    "command": "\(grafttyCLIPath) team hook codex \(event.rawValue)",
                ],
            ],
        ]
    }

    private static func isGrafttyCodexHookCommand(_ command: String) -> Bool {
        command.hasPrefix(grafttyCommandPrefix) || command.contains(" team hook codex ")
    }

    private func writeManagedConfig() throws {
        let fm = FileManager.default
        let source = sourceDirectory.appendingPathComponent("config.toml")
        let destination = mirrorDirectory.appendingPathComponent("config.toml")
        let data = (try? Data(contentsOf: source)) ?? Data()
        if (try? fm.destinationOfSymbolicLink(atPath: destination.path)) != nil {
            try fm.removeItem(at: destination)
        }
        try data.write(to: destination, options: .atomic)
    }

    private func acquireRebuildLock() throws -> Int32 {
        let path = mirrorDirectory.appendingPathComponent(".graftty-mirror.lock").path
        let permissions = S_IRUSR | S_IWUSR
        #if canImport(Darwin)
        let fd = Darwin.open(path, O_RDWR | O_CREAT, permissions)
        #elseif canImport(Glibc)
        let fd = Glibc.open(path, O_RDWR | O_CREAT, mode_t(permissions))
        #else
        #error("Unsupported platform")
        #endif
        guard fd >= 0 else { throw currentPOSIXError() }
        #if canImport(Darwin)
        let result = Darwin.lockf(fd, F_LOCK, 0)
        #elseif canImport(Glibc)
        let result = Glibc.lockf(fd, F_LOCK, 0)
        #endif
        guard result == 0 else {
            #if canImport(Darwin)
            _ = Darwin.close(fd)
            #elseif canImport(Glibc)
            _ = Glibc.close(fd)
            #endif
            throw currentPOSIXError()
        }
        return fd
    }

    private func currentPOSIXError() -> NSError {
        NSError(domain: NSPOSIXErrorDomain, code: Int(errno))
    }

    /// Migrates configuration mutations left in the generated config used by
    /// releases before mirror version 2. The old wrapper refreshed that file
    /// from the durable config immediately before running Codex, so a newer
    /// legacy file is the authoritative post-mutation copy. If the durable file
    /// is newer, preserve the legacy bytes beside it instead of guessing which
    /// concurrent edits should win.
    private func migrateLegacyConfigIfNeeded() throws {
        let fm = FileManager.default
        let marker = mirrorDirectory.appendingPathComponent(".graftty-mirror-version")
        guard !fm.fileExists(atPath: marker.path) else { return }

        let legacy = mirrorDirectory.appendingPathComponent("config.toml")
        guard fm.fileExists(atPath: legacy.path),
              (try? fm.destinationOfSymbolicLink(atPath: legacy.path)) == nil else {
            return
        }

        let durable = sourceDirectory.appendingPathComponent("config.toml")
        let legacyData = try Data(contentsOf: legacy)
        let durableData = (try? Data(contentsOf: durable)) ?? Data()
        let migratedData = Self.restoringDurableHooksSetting(
            in: legacyData,
            durableConfig: durableData
        )
        let reconciledData = Self.mergingLegacyAdministrationState(
            from: migratedData,
            into: durableData
        )
        guard reconciledData != durableData else { return }

        let legacyDate = try legacy.resourceValues(forKeys: [.contentModificationDateKey])
            .contentModificationDate ?? .distantPast
        let durableDate = (try? durable.resourceValues(forKeys: [.contentModificationDateKey]))?
            .contentModificationDate ?? .distantPast

        if legacyDate >= durableDate {
            if fm.fileExists(atPath: durable.path) {
                let backup = availableBackupURL(named: "config.toml.graftty-pre-migration")
                try fm.copyItem(at: durable, to: backup)
            }
            try reconciledData.write(to: durable, options: .atomic)
        } else {
            let backup = availableBackupURL(named: "config.toml.graftty-legacy")
            try migratedData.write(to: backup, options: .atomic)
        }
    }

    private func availableBackupURL(named name: String) -> URL {
        let fm = FileManager.default
        var candidate = sourceDirectory.appendingPathComponent(name)
        var suffix = 1
        while fm.fileExists(atPath: candidate.path)
            || (try? fm.destinationOfSymbolicLink(atPath: candidate.path)) != nil {
            candidate = sourceDirectory.appendingPathComponent("\(name)-\(suffix)")
            suffix += 1
        }
        return candidate
    }

    /// The legacy mirror forced `[features].hooks = true`. Restore the user's
    /// durable value (or absence) while retaining every other legacy byte.
    private static func restoringDurableHooksSetting(
        in legacyConfig: Data,
        durableConfig: Data
    ) -> Data {
        guard let legacy = String(data: legacyConfig, encoding: .utf8),
              let durable = String(data: durableConfig, encoding: .utf8) else {
            return legacyConfig
        }
        let durableHooksLine = hooksSettingLine(in: durable)
        let restored = replacingHooksSetting(in: legacy, with: durableHooksLine)
        return Data(restored.utf8)
    }

    private static func hooksSettingLine(in config: String) -> String? {
        var inFeatures = false
        for line in config.components(separatedBy: "\n") {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.hasPrefix("[") && trimmed.hasSuffix("]") {
                inFeatures = trimmed == "[features]"
            } else if inFeatures, isHooksSetting(trimmed) {
                return line
            }
        }
        return nil
    }

    private static func replacingHooksSetting(in config: String, with replacement: String?) -> String {
        var inFeatures = false
        var didRestore = false
        var output: [String] = []
        for line in config.components(separatedBy: "\n") {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.hasPrefix("[") && trimmed.hasSuffix("]") {
                inFeatures = trimmed == "[features]"
                output.append(line)
                continue
            }
            if inFeatures, isHooksSetting(trimmed) {
                if let replacement, !didRestore {
                    output.append(replacement)
                    didRestore = true
                }
                continue
            }
            output.append(line)
        }
        return output.joined(separator: "\n")
    }

    private static func isHooksSetting(_ line: String) -> Bool {
        line.hasPrefix("hooks ") || line.hasPrefix("hooks=") || line.hasPrefix("hooks\t")
    }

    /// Legacy plugin commands changed only Codex's administrative table
    /// families. Replace those tables as one newer snapshot while retaining
    /// unrelated durable settings that may have changed independently.
    private static func mergingLegacyAdministrationState(
        from legacyConfig: Data,
        into durableConfig: Data
    ) -> Data {
        guard !durableConfig.isEmpty,
              let legacy = String(data: legacyConfig, encoding: .utf8),
              let durable = String(data: durableConfig, encoding: .utf8) else {
            return legacyConfig
        }
        let durableSections = tomlSections(in: durable)
        let legacySections = tomlSections(in: legacy)
        let legacyFeatures = legacySections.first { $0.table == "features" }
        let durableFeatures = durableSections.first { $0.table == "features" }
        let retained = durableSections.filter { section in
            guard let table = section.table else { return true }
            return !isCodexAdministrationTable(table)
                && (table != "features" || legacyFeatures == nil)
        }
        let administration = legacySections.filter { section in
            guard let table = section.table else { return false }
            return isCodexAdministrationTable(table)
        }
        var lines = retained.flatMap(\.lines)
        if let legacyFeatures {
            appendSection(
                mergingLegacyFeatures(legacyFeatures, into: durableFeatures),
                to: &lines
            )
        }
        for section in administration {
            appendSection(section, to: &lines)
        }
        return Data(lines.joined(separator: "\n").utf8)
    }

    /// The legacy snapshot began as a copy of the durable config, so its
    /// feature values contain the post-command state. Retain durable-only keys
    /// as protection against an independent edit after that snapshot.
    private static func mergingLegacyFeatures(
        _ legacy: TOMLSection,
        into durable: TOMLSection?
    ) -> TOMLSection {
        guard let durable else { return legacy }
        let legacyKeys = Set(legacy.lines.compactMap(tomlAssignmentKey))
        let durableOnly = durable.lines.filter { line in
            guard let key = tomlAssignmentKey(in: line) else { return false }
            return !legacyKeys.contains(key)
        }
        guard !durableOnly.isEmpty else { return legacy }

        var lines = legacy.lines
        let endedWithBlankLine = lines.last == ""
        while lines.last == "" {
            lines.removeLast()
        }
        lines.append(contentsOf: durableOnly)
        if endedWithBlankLine {
            lines.append("")
        }
        return TOMLSection(table: legacy.table, lines: lines)
    }

    private static func tomlAssignmentKey(in line: String) -> String? {
        let trimmed = line.trimmingCharacters(in: .whitespaces)
        guard !trimmed.isEmpty,
              !trimmed.hasPrefix("#"),
              let equals = trimmed.firstIndex(of: "=") else {
            return nil
        }
        let key = trimmed[..<equals].trimmingCharacters(in: .whitespaces)
        return key.isEmpty ? nil : key
    }

    private static func appendSection(_ section: TOMLSection, to lines: inout [String]) {
        if !lines.isEmpty, lines.last != "" {
            lines.append("")
        }
        lines.append(contentsOf: section.lines)
    }

    private struct TOMLSection {
        let table: String?
        var lines: [String]
    }

    private static func tomlSections(in config: String) -> [TOMLSection] {
        var sections = [TOMLSection(table: nil, lines: [])]
        for line in config.components(separatedBy: "\n") {
            if let table = tomlTableName(in: line) {
                sections.append(TOMLSection(table: table, lines: [line]))
            } else {
                sections[sections.count - 1].lines.append(line)
            }
        }
        return sections
    }

    private static func tomlTableName(in line: String) -> String? {
        let trimmed = line.trimmingCharacters(in: .whitespaces)
        if trimmed.hasPrefix("[["), trimmed.hasSuffix("]]"), trimmed.count > 4 {
            return String(trimmed.dropFirst(2).dropLast(2))
        }
        if trimmed.hasPrefix("["), trimmed.hasSuffix("]"), trimmed.count > 2 {
            return String(trimmed.dropFirst().dropLast())
        }
        return nil
    }

    private static func isCodexAdministrationTable(_ table: String) -> Bool {
        ["marketplaces", "plugins", "mcp_servers"].contains { namespace in
            table == namespace || table.hasPrefix("\(namespace).")
        }
    }

}
