import Foundation
#if canImport(Darwin)
import Darwin
#elseif canImport(Glibc)
import Glibc
#endif

/// @spec TEAM-IDLE-1.1: When Graftty synthesizes a managed CODEX_HOME, the application shall union the user's Codex hooks with Graftty's current SessionStart hook and remove stale Graftty delivery hooks.
/// Synthesizes a CODEX_HOME directory that mirrors the user's `~/.codex/`
/// via symlinks, with `hooks.json` and the managed `config.toml` snapshot
/// generated by Graftty and runtime control state kept mirror-local.
/// Configuration mutations run against the durable home; the wrapper enables
/// hooks with a launch-scoped CLI override. Idempotent - runs via
/// `graftty internal sync-codex-home` before managed sessions.
public struct CodexHomeMirror: Sendable {
    public static let grafttyCommandPrefix = "graftty team hook codex"

    private static let generatedEntryNames: Set<String> = [
        "hooks.json",
        "config.toml",
        ".graftty-mirror-version",
        ".graftty-mirror.lock",
    ]
    private static let runtimeDirectoryNames: Set<String> = [
        "app-server-control",
    ]
    private static let managedEntryNames = generatedEntryNames.union(runtimeDirectoryNames)
    private static let currentMirrorVersion = "3"
    private static let basicQuote: UInt8 = 34
    private static let literalQuote: UInt8 = 39
    private static let commentMarker: UInt8 = 35
    private static let backslash: UInt8 = 92

    public let sourceDirectory: URL
    public let mirrorDirectory: URL
    public let grafttyCLIPath: String

    public init(sourceDirectory: URL, mirrorDirectory: URL, grafttyCLIPath: String) {
        self.sourceDirectory = sourceDirectory
        self.mirrorDirectory = mirrorDirectory
        self.grafttyCLIPath = grafttyCLIPath
    }

    /// `<rootDirectory>/codex-home/` where rootDirectory = AgentHookInstaller's root.
    public static func defaultMirrorDirectory(rootDirectory: URL = AgentHookInstaller.rootDirectory()) -> URL {
        rootDirectory.appendingPathComponent("codex-home", isDirectory: true)
    }

    public static func defaultSourceDirectory() -> URL {
        URL(fileURLWithPath: NSHomeDirectory())
            .appendingPathComponent(".codex", isDirectory: true)
    }

    /// Strip-and-rewrite. Idempotent.
    public func rebuild() throws {
        let fm = FileManager.default
        try fm.createDirectory(at: mirrorDirectory, withIntermediateDirectories: true)
        let lockFD = try acquireRebuildLock()
        defer {
            #if canImport(Darwin)
            _ = flock(lockFD, LOCK_UN)
            _ = Darwin.close(lockFD)
            #elseif canImport(Glibc)
            _ = flock(lockFD, LOCK_UN)
            _ = Glibc.close(lockFD)
            #endif
        }
        try fm.createDirectory(at: sourceDirectory, withIntermediateDirectories: true)

        // A managed runtime can create new durable state after an earlier sync.
        // Rescue every real non-runtime entry before source inventory and
        // pruning, even when the mirror schema marker is already current.
        try migrateManagedMirrorEntries()
        try migrateLegacyConfigIfNeeded()

        // Inventory failures must abort the rebuild. Treating an unreadable
        // directory as empty could prune valid mirror state and still advance
        // the migration marker, preventing a safe retry.
        let sourceEntries = try fm.contentsOfDirectory(atPath: sourceDirectory.path)
        let mirroredEntries = sourceEntries.filter { !Self.managedEntryNames.contains($0) }

        // Pass 1: write/refresh symlinks for every durable source entry.
        for name in mirroredEntries {
            let linkPath = mirrorDirectory.appendingPathComponent(name)
            let target = sourceDirectory.appendingPathComponent(name)
            try replaceSymlink(at: linkPath, target: target)
        }

        // Pass 2: prune mirror entries that no longer belong to the durable
        // source, excluding Graftty-managed files and runtime directories.
        let mirrorEntries = try fm.contentsOfDirectory(atPath: mirrorDirectory.path)
        let mirroredSet = Set(mirroredEntries)
        for name in mirrorEntries
        where !Self.managedEntryNames.contains(name) && !mirroredSet.contains(name) {
            try? fm.removeItem(at: mirrorDirectory.appendingPathComponent(name))
        }

        // Pass 3: prepare mirror-local runtime directories and write
        // Graftty-owned files.
        try prepareRuntimeDirectories()
        try writeManagedConfig()
        try writeMergedHooks()
        try "\(Self.currentMirrorVersion)\n".write(
            to: mirrorDirectory.appendingPathComponent(".graftty-mirror-version"),
            atomically: true,
            encoding: .utf8
        )
    }

    private func replaceSymlink(at link: URL, target: URL) throws {
        let fm = FileManager.default
        // Existing symlink to the same target — keep as-is (idempotent).
        if let existing = try? fm.destinationOfSymbolicLink(atPath: link.path),
           existing == target.path {
            return
        }
        try? fm.removeItem(at: link)
        do {
            try fm.createSymbolicLink(atPath: link.path, withDestinationPath: target.path)
        } catch {
            if let existing = try? fm.destinationOfSymbolicLink(atPath: link.path),
               existing == target.path {
                return
            }
            throw error
        }
    }

    private func writeMergedHooks() throws {
        let userHooksURL = sourceDirectory.appendingPathComponent("hooks.json")
        var root: [String: Any] = [:]
        if let data = try readDataIfPresent(at: userHooksURL),
           let parsed = try? JSONSerialization.jsonObject(with: data) as? [String: Any] {
            root = parsed
        }
        var hooks = (root["hooks"] as? [String: Any]) ?? [:]
        for event in TeamHookEvent.allCases {
            let key = event.camelCaseKey
            let existing = (hooks[key] as? [[String: Any]]) ?? []
            let stripped = existing.filter { group in
                let handlers = (group["hooks"] as? [[String: Any]]) ?? []
                return !handlers.contains(where: { handler in
                    guard let command = handler["command"] as? String else { return false }
                    return Self.isGrafttyCodexHookCommand(command)
                })
            }
            hooks[key] = event == .sessionStart
                ? stripped + [grafttyMatcherGroup(event: event)]
                : stripped
        }
        root["hooks"] = hooks

        let outURL = mirrorDirectory.appendingPathComponent("hooks.json")
        let data = try JSONSerialization.data(withJSONObject: root, options: [.prettyPrinted, .sortedKeys])
        try data.write(to: outURL, options: .atomic)
    }

    private func grafttyMatcherGroup(event: TeamHookEvent) -> [String: Any] {
        [
            "hooks": [
                [
                    "type": "command",
                    "command": "\(grafttyCLIPath) team hook codex \(event.rawValue)",
                ],
            ],
        ]
    }

    private static func isGrafttyCodexHookCommand(_ command: String) -> Bool {
        command.hasPrefix(grafttyCommandPrefix) || command.contains(" team hook codex ")
    }

    private func writeManagedConfig() throws {
        let fm = FileManager.default
        let source = sourceDirectory.appendingPathComponent("config.toml")
        let destination = mirrorDirectory.appendingPathComponent("config.toml")
        let data = try readDataIfPresent(at: source) ?? Data()
        if (try? fm.destinationOfSymbolicLink(atPath: destination.path)) != nil {
            try fm.removeItem(at: destination)
        }
        try data.write(to: destination, options: .atomic)
    }

    private func acquireRebuildLock() throws -> Int32 {
        let path = mirrorDirectory.appendingPathComponent(".graftty-mirror.lock").path
        let permissions = S_IRUSR | S_IWUSR
        #if canImport(Darwin)
        let fd = Darwin.open(path, O_RDWR | O_CREAT, permissions)
        #elseif canImport(Glibc)
        let fd = Glibc.open(path, O_RDWR | O_CREAT, mode_t(permissions))
        #else
        #error("Unsupported platform")
        #endif
        guard fd >= 0 else { throw currentPOSIXError() }
        let result = flock(fd, LOCK_EX)
        guard result == 0 else {
            #if canImport(Darwin)
            _ = Darwin.close(fd)
            #elseif canImport(Glibc)
            _ = Glibc.close(fd)
            #endif
            throw currentPOSIXError()
        }
        return fd
    }

    private func currentPOSIXError() -> NSError {
        NSError(domain: NSPOSIXErrorDomain, code: Int(errno))
    }

    /// Migrates configuration mutations left in the generated home by older
    /// wrapper releases. The old wrapper refreshed its config from the durable
    /// copy immediately before running Codex, so a newer legacy file contains
    /// the post-mutation administration state. If the durable file is newer,
    /// preserve a sanitized recovery copy instead of guessing which concurrent
    /// edits should win.
    private func migrateLegacyConfigIfNeeded() throws {
        let marker = mirrorDirectory.appendingPathComponent(".graftty-mirror-version")
        let version = (try? String(contentsOf: marker, encoding: .utf8))?
            .trimmingCharacters(in: .whitespacesAndNewlines)
        guard version != Self.currentMirrorVersion else { return }

        try migrateLegacyConfigIfPresent()
    }

    private func migrateManagedMirrorEntries() throws {
        let fm = FileManager.default
        let entries = try fm.contentsOfDirectory(atPath: mirrorDirectory.path)
        for name in entries where !Self.managedEntryNames.contains(name) {
            let legacy = mirrorDirectory.appendingPathComponent(name)
            guard (try? fm.destinationOfSymbolicLink(atPath: legacy.path)) == nil else {
                continue
            }
            let durable = sourceDirectory.appendingPathComponent(name)
            if !entryExists(at: durable) {
                try fm.moveItem(at: legacy, to: durable)
                continue
            }

            let backup = availableBackupURL(named: "\(name).graftty-legacy")
            try mergeLegacyEntry(from: legacy, into: durable, backupAt: backup)
        }
    }

    private func prepareRuntimeDirectories() throws {
        for name in Self.runtimeDirectoryNames {
            let directory = mirrorDirectory.appendingPathComponent(name, isDirectory: true)
            guard let values = try entryTypeValuesIfPresent(at: directory) else {
                try createPrivateDirectory(at: directory)
                continue
            }
            if isRealDirectory(values) {
                continue
            }
            try removeNonDirectoryEntry(at: directory)
            try createPrivateDirectory(at: directory)
        }
    }

    private func entryTypeValuesIfPresent(at url: URL) throws -> URLResourceValues? {
        do {
            return try url.resourceValues(forKeys: [.isDirectoryKey, .isSymbolicLinkKey])
        } catch {
            guard isNoSuchFileError(error) else { throw error }
            return nil
        }
    }

    private func isRealDirectory(_ values: URLResourceValues) -> Bool {
        values.isDirectory == true && values.isSymbolicLink != true
    }

    /// `unlink` cannot remove a directory, so a real runtime directory that
    /// appears after inspection is preserved instead of recursively deleted.
    private func removeNonDirectoryEntry(at url: URL) throws {
        #if canImport(Darwin)
        let result = url.path.withCString { Darwin.unlink($0) }
        #elseif canImport(Glibc)
        let result = url.path.withCString { Glibc.unlink($0) }
        #endif
        guard result != 0 else { return }

        let unlinkError = currentPOSIXError()
        if unlinkError.code == Int(ENOENT) {
            return
        }
        guard let currentValues = try entryTypeValuesIfPresent(at: url) else {
            return
        }
        if isRealDirectory(currentValues) {
            return
        }
        throw unlinkError
    }

    private func createPrivateDirectory(at url: URL) throws {
        try FileManager.default.createDirectory(
            at: url,
            withIntermediateDirectories: true,
            attributes: [.posixPermissions: NSNumber(value: Int16(0o700))]
        )
    }

    private func mergeLegacyEntry(from legacy: URL, into durable: URL, backupAt backup: URL) throws {
        let fm = FileManager.default
        guard entryExists(at: durable) else {
            try fm.createDirectory(at: durable.deletingLastPathComponent(), withIntermediateDirectories: true)
            try fm.moveItem(at: legacy, to: durable)
            return
        }

        let legacyValues = try legacy.resourceValues(forKeys: [.isDirectoryKey, .isSymbolicLinkKey])
        let durableValues = try durable.resourceValues(forKeys: [.isDirectoryKey, .isSymbolicLinkKey])
        if legacyValues.isDirectory == true,
           legacyValues.isSymbolicLink != true,
           durableValues.isDirectory == true,
           durableValues.isSymbolicLink != true {
            for name in try fm.contentsOfDirectory(atPath: legacy.path) {
                try mergeLegacyEntry(
                    from: legacy.appendingPathComponent(name),
                    into: durable.appendingPathComponent(name),
                    backupAt: backup.appendingPathComponent(name)
                )
            }
            if (try fm.contentsOfDirectory(atPath: legacy.path)).isEmpty {
                try fm.removeItem(at: legacy)
            }
            return
        }

        try fm.createDirectory(at: backup.deletingLastPathComponent(), withIntermediateDirectories: true)
        try fm.moveItem(at: legacy, to: backup)
    }

    private func entryExists(at url: URL) -> Bool {
        FileManager.default.fileExists(atPath: url.path)
            || (try? FileManager.default.destinationOfSymbolicLink(atPath: url.path)) != nil
    }

    /// Absence is a valid empty configuration, but every other read failure
    /// must abort the sync so the wrapper can fall back to the durable home.
    private func readDataIfPresent(at url: URL) throws -> Data? {
        do {
            return try Data(contentsOf: url)
        } catch {
            guard isNoSuchFileError(error) else { throw error }
            return nil
        }
    }

    private func isNoSuchFileError(_ error: Error) -> Bool {
        let nsError = error as NSError
        if nsError.domain == NSCocoaErrorDomain,
           nsError.code == NSFileReadNoSuchFileError {
            return true
        }
        if nsError.domain == NSPOSIXErrorDomain,
           nsError.code == Int(ENOENT) {
            return true
        }
        if let underlying = nsError.userInfo[NSUnderlyingErrorKey] as? NSError,
           underlying.domain == NSPOSIXErrorDomain,
           underlying.code == Int(ENOENT) {
            return true
        }
        return false
    }

    private func migrateLegacyConfigIfPresent() throws {
        let fm = FileManager.default

        let legacy = mirrorDirectory.appendingPathComponent("config.toml")
        guard fm.fileExists(atPath: legacy.path),
              (try? fm.destinationOfSymbolicLink(atPath: legacy.path)) == nil else {
            return
        }

        let durable = sourceDirectory.appendingPathComponent("config.toml")
        let legacyData = try Data(contentsOf: legacy)
        let durableData = try readDataIfPresent(at: durable) ?? Data()
        let migratedData = Self.restoringDurableHooksSetting(
            in: legacyData,
            durableConfig: durableData
        )
        let reconciledData = Self.mergingLegacyAdministrationState(
            from: migratedData,
            into: durableData
        )
        let legacyDate = try legacy.resourceValues(forKeys: [.contentModificationDateKey])
            .contentModificationDate ?? .distantPast
        let durableDate = (try? durable.resourceValues(forKeys: [.contentModificationDateKey]))?
            .contentModificationDate ?? .distantPast

        if legacyDate >= durableDate {
            if migratedData != reconciledData {
                let backup = availableBackupURL(named: "config.toml.graftty-legacy")
                try migratedData.write(to: backup, options: .atomic)
            }
            guard reconciledData != durableData else { return }
            if fm.fileExists(atPath: durable.path) {
                let backup = availableBackupURL(named: "config.toml.graftty-pre-migration")
                try fm.copyItem(at: durable, to: backup)
            }
            try reconciledData.write(to: durable, options: .atomic)
        } else if migratedData != durableData {
            let backup = availableBackupURL(named: "config.toml.graftty-legacy")
            try migratedData.write(to: backup, options: .atomic)
        }
    }

    private func availableBackupURL(named name: String) -> URL {
        let fm = FileManager.default
        var candidate = sourceDirectory.appendingPathComponent(name)
        var suffix = 1
        while fm.fileExists(atPath: candidate.path)
            || (try? fm.destinationOfSymbolicLink(atPath: candidate.path)) != nil {
            candidate = sourceDirectory.appendingPathComponent("\(name)-\(suffix)")
            suffix += 1
        }
        return candidate
    }

    /// The legacy mirror forced `[features].hooks = true`. Restore the user's
    /// durable value (or absence) while retaining every other legacy byte.
    private static func restoringDurableHooksSetting(
        in legacyConfig: Data,
        durableConfig: Data
    ) -> Data {
        guard let legacy = String(data: legacyConfig, encoding: .utf8),
              let durable = String(data: durableConfig, encoding: .utf8) else {
            return legacyConfig
        }
        let durableHooksLine = hooksSettingLine(in: durable)
        let restored = replacingHooksSetting(in: legacy, with: durableHooksLine)
        return Data(restored.utf8)
    }

    private static func hooksSettingLine(in config: String) -> String? {
        var inFeatures = false
        for scannedLine in scanningTOMLLines(in: config) {
            guard scannedLine.isStructural else { continue }
            let line = scannedLine.text
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if let table = tomlTableName(in: line) {
                inFeatures = table == ["features"]
            } else if inFeatures, isHooksSetting(trimmed) {
                return line
            }
        }
        return nil
    }

    private static func replacingHooksSetting(in config: String, with replacement: String?) -> String {
        var inFeatures = false
        var didRestore = false
        var output: [String] = []
        for scannedLine in scanningTOMLLines(in: config) {
            let line = scannedLine.text
            guard scannedLine.isStructural else {
                output.append(line)
                continue
            }
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if let table = tomlTableName(in: line) {
                inFeatures = table == ["features"]
                output.append(line)
                continue
            }
            if inFeatures, isHooksSetting(trimmed) {
                if let replacement, !didRestore {
                    output.append(replacement)
                    didRestore = true
                }
                continue
            }
            output.append(line)
        }
        return output.joined(separator: "\n")
    }

    private static func isHooksSetting(_ line: String) -> Bool {
        tomlAssignmentKey(in: line) == ["hooks"]
    }

    /// Legacy administration commands changed Codex's feature and
    /// administrative table families. Reconcile those values while retaining
    /// unrelated durable settings that may have changed independently.
    private static func mergingLegacyAdministrationState(
        from legacyConfig: Data,
        into durableConfig: Data
    ) -> Data {
        guard !durableConfig.isEmpty,
              let legacy = String(data: legacyConfig, encoding: .utf8),
              let durable = String(data: durableConfig, encoding: .utf8) else {
            return legacyConfig
        }
        let durableSections = tomlSections(in: durable)
        let legacySections = tomlSections(in: legacy)
        let legacyRoot = legacySections[0]
        let durableRoot = durableSections[0]
        let legacyFeatures = legacySections.first { $0.table == ["features"] }
        let durableFeatures = durableSections.first { $0.table == ["features"] }
        let retained = durableSections.filter { section in
            guard let table = section.table else { return false }
            return !isCodexAdministrationTable(table)
                && (table != ["features"] || legacyFeatures == nil)
        }
        let administration = legacySections.filter { section in
            guard let table = section.table else { return false }
            return isCodexAdministrationTable(table)
        }
        var lines = mergingLegacyRootAssignments(legacyRoot, into: durableRoot).lines
        for section in retained {
            appendSection(section, to: &lines)
        }
        if let legacyFeatures {
            appendSection(
                mergingLegacyFeatures(legacyFeatures, into: durableFeatures),
                to: &lines
            )
        }
        for section in administration {
            appendSection(section, to: &lines)
        }
        return Data(lines.joined(separator: "\n").utf8)
    }

    /// Root dotted-key and inline-table assignments are semantically the same
    /// administration namespaces as their table-header forms. Keep unrelated
    /// durable root assignments, but let the legacy snapshot's presence or
    /// absence determine the administrative ones.
    private static func mergingLegacyRootAssignments(
        _ legacy: TOMLSection,
        into durable: TOMLSection
    ) -> TOMLSection {
        let legacyLayout = tomlAssignmentLayout(in: legacy.lines)
        let durableLayout = tomlAssignmentLayout(in: durable.lines)
        let retainedDurable = durableLayout.blocks.filter {
            !isCodexAdministrationAssignment($0.key)
        }
        let legacyAdministration = legacyLayout.blocks.filter {
            isCodexAdministrationAssignment($0.key)
        }
        return TOMLSection(
            table: nil,
            lines: durableLayout.prefixLines
                + retainedDurable.flatMap(\.lines)
                + legacyAdministration.flatMap(\.lines)
        )
    }

    private static func isCodexAdministrationAssignment(_ key: [String]) -> Bool {
        guard let namespace = key.first else { return false }
        return namespace == "marketplaces"
            || namespace == "plugins"
            || namespace == "mcp_servers"
    }

    /// The legacy snapshot began as a copy of the durable config, so its
    /// feature values contain the post-command state. Retain durable-only keys
    /// as protection against an independent edit after that snapshot.
    private static func mergingLegacyFeatures(
        _ legacy: TOMLSection,
        into durable: TOMLSection?
    ) -> TOMLSection {
        guard let durable else { return legacy }
        let legacyKeys = Set(tomlAssignmentBlocks(in: legacy.lines).map(\.key))
        let durableOnly = tomlAssignmentBlocks(in: durable.lines)
            .filter { !legacyKeys.contains($0.key) }
            .flatMap(\.lines)
        guard !durableOnly.isEmpty else { return legacy }

        var lines = legacy.lines
        let endedWithBlankLine = lines.last == ""
        while lines.last == "" {
            lines.removeLast()
        }
        lines.append(contentsOf: durableOnly)
        if endedWithBlankLine {
            lines.append("")
        }
        return TOMLSection(table: legacy.table, lines: lines)
    }

    private static func tomlAssignmentKey(in line: String) -> [String]? {
        let trimmed = line.trimmingCharacters(in: .whitespaces)
        guard !trimmed.isEmpty,
              !trimmed.hasPrefix("#") else {
            return nil
        }
        let bytes = Array(trimmed.utf8)
        var quote: UInt8?
        for index in bytes.indices {
            if let activeQuote = quote {
                if bytes[index] == activeQuote,
                   activeQuote == literalQuote || !isEscaped(bytes, at: index) {
                    quote = nil
                }
            } else if bytes[index] == basicQuote || bytes[index] == literalQuote {
                quote = bytes[index]
            } else if bytes[index] == 61 {
                return tomlDottedKeyComponents(in: bytes[..<index])
            } else if bytes[index] == commentMarker {
                return nil
            }
        }
        return nil
    }

    private struct TOMLAssignmentBlock {
        let key: [String]
        var lines: [String]
    }

    private struct TOMLAssignmentLayout {
        var prefixLines: [String]
        var blocks: [TOMLAssignmentBlock]
    }

    /// Groups a top-level assignment with every continuation line up to the
    /// next top-level assignment. This preserves multiline strings and arrays
    /// when durable-only feature values are carried into the legacy section.
    private static func tomlAssignmentBlocks(in lines: [String]) -> [TOMLAssignmentBlock] {
        tomlAssignmentLayout(in: lines).blocks
    }

    private static func tomlAssignmentLayout(in lines: [String]) -> TOMLAssignmentLayout {
        let scannedLines = scanningTOMLLines(in: lines.joined(separator: "\n"))
        var prefixLines: [String] = []
        var blocks: [TOMLAssignmentBlock] = []
        var current: TOMLAssignmentBlock?
        for line in scannedLines {
            if line.isStructural, let key = tomlAssignmentKey(in: line.text) {
                if let current {
                    blocks.append(current)
                }
                current = TOMLAssignmentBlock(key: key, lines: [line.text])
            } else if current != nil {
                current?.lines.append(line.text)
            } else {
                prefixLines.append(line.text)
            }
        }
        if let current {
            blocks.append(current)
        }
        return TOMLAssignmentLayout(prefixLines: prefixLines, blocks: blocks)
    }

    private static func appendSection(_ section: TOMLSection, to lines: inout [String]) {
        if !lines.isEmpty, lines.last != "" {
            lines.append("")
        }
        lines.append(contentsOf: section.lines)
    }

    private struct TOMLSection {
        let table: [String]?
        var lines: [String]
    }

    private struct TOMLScannedLine {
        let text: String
        let isStructural: Bool
    }

    private static func tomlSections(in config: String) -> [TOMLSection] {
        var sections = [TOMLSection(table: nil, lines: [])]
        for scannedLine in scanningTOMLLines(in: config) {
            let line = scannedLine.text
            guard scannedLine.isStructural else {
                sections[sections.count - 1].lines.append(line)
                continue
            }
            if let table = tomlTableName(in: line) {
                sections.append(TOMLSection(table: table, lines: [line]))
            } else {
                sections[sections.count - 1].lines.append(line)
            }
        }
        return sections
    }

    /// Identifies lines whose apparent TOML structure is outside multiline
    /// basic or literal strings. The migration only needs table boundaries and
    /// one boolean key; preserving original lines keeps every other byte-level
    /// representation intact.
    private static func scanningTOMLLines(in config: String) -> [TOMLScannedLine] {
        var multilineQuote: UInt8?
        return config.components(separatedBy: "\n").map { line in
            let scanned = TOMLScannedLine(text: line, isStructural: multilineQuote == nil)
            updateMultilineQuoteState(in: line, multilineQuote: &multilineQuote)
            return scanned
        }
    }

    private static func updateMultilineQuoteState(
        in line: String,
        multilineQuote: inout UInt8?
    ) {
        let bytes = Array(line.utf8)
        var singleLineQuote: UInt8?
        var index = 0
        while index < bytes.count {
            if let quote = multilineQuote {
                if hasTripleQuote(bytes, at: index, quote: quote),
                   quote == literalQuote || !isEscaped(bytes, at: index) {
                    multilineQuote = nil
                    index += 3
                } else {
                    index += 1
                }
                continue
            }

            if let quote = singleLineQuote {
                if bytes[index] == quote,
                   quote == literalQuote || !isEscaped(bytes, at: index) {
                    singleLineQuote = nil
                }
                index += 1
                continue
            }

            if bytes[index] == commentMarker {
                break
            }
            if bytes[index] == basicQuote || bytes[index] == literalQuote {
                let quote = bytes[index]
                if hasTripleQuote(bytes, at: index, quote: quote) {
                    multilineQuote = quote
                    index += 3
                } else {
                    singleLineQuote = quote
                    index += 1
                }
                continue
            }
            index += 1
        }
    }

    private static func hasTripleQuote(_ bytes: [UInt8], at index: Int, quote: UInt8) -> Bool {
        index + 2 < bytes.count
            && bytes[index] == quote
            && bytes[index + 1] == quote
            && bytes[index + 2] == quote
    }

    private static func isEscaped(_ bytes: [UInt8], at index: Int) -> Bool {
        var backslashCount = 0
        var cursor = index
        while cursor > 0, bytes[cursor - 1] == backslash {
            backslashCount += 1
            cursor -= 1
        }
        return backslashCount.isMultiple(of: 2) == false
    }

    private static func tomlTableName(in line: String) -> [String]? {
        let trimmed = tomlContentBeforeComment(in: line)
            .trimmingCharacters(in: .whitespaces)
        if trimmed.hasPrefix("[["), trimmed.hasSuffix("]]"), trimmed.count > 4 {
            return tomlDottedKeyComponents(in: trimmed.dropFirst(2).dropLast(2).utf8)
        }
        if trimmed.hasPrefix("["), trimmed.hasSuffix("]"), trimmed.count > 2 {
            return tomlDottedKeyComponents(in: trimmed.dropFirst().dropLast().utf8)
        }
        return nil
    }

    /// Parses the semantic components of a TOML dotted key so whitespace and
    /// quoted spellings do not change namespace matching.
    private static func tomlDottedKeyComponents<C: Collection>(in bytes: C) -> [String]?
    where C.Element == UInt8 {
        let bytes = Array(bytes)
        var components: [String] = []
        var index = 0

        func skipWhitespace() {
            while index < bytes.count, bytes[index] == 32 || bytes[index] == 9 {
                index += 1
            }
        }

        skipWhitespace()
        while index < bytes.count {
            let component: String
            if bytes[index] == basicQuote {
                guard let parsed = parseBasicQuotedKey(in: bytes, index: &index) else { return nil }
                component = parsed
            } else if bytes[index] == literalQuote {
                index += 1
                let start = index
                while index < bytes.count, bytes[index] != literalQuote {
                    index += 1
                }
                guard index < bytes.count else { return nil }
                component = String(decoding: bytes[start..<index], as: UTF8.self)
                index += 1
            } else {
                let start = index
                while index < bytes.count, isBareTOMLKeyByte(bytes[index]) {
                    index += 1
                }
                guard index > start else { return nil }
                component = String(decoding: bytes[start..<index], as: UTF8.self)
            }
            components.append(component)
            skipWhitespace()
            guard index < bytes.count else { break }
            guard bytes[index] == 46 else { return nil }
            index += 1
            skipWhitespace()
            guard index < bytes.count else { return nil }
        }
        return components.isEmpty ? nil : components
    }

    private static func parseBasicQuotedKey(in bytes: [UInt8], index: inout Int) -> String? {
        index += 1
        var result = ""
        var literalStart = index

        func appendLiteral(until end: Int) {
            guard literalStart < end else { return }
            result += String(decoding: bytes[literalStart..<end], as: UTF8.self)
        }

        while index < bytes.count {
            if bytes[index] == basicQuote {
                appendLiteral(until: index)
                index += 1
                return result
            }
            guard bytes[index] == backslash else {
                index += 1
                continue
            }

            appendLiteral(until: index)
            index += 1
            guard index < bytes.count else { return nil }
            switch bytes[index] {
            case 34: result.append("\"")
            case 92: result.append("\\")
            case 98: result.append("\u{8}")
            case 102: result.append("\u{C}")
            case 110: result.append("\n")
            case 114: result.append("\r")
            case 116: result.append("\t")
            case 117, 85:
                let digitCount = bytes[index] == 117 ? 4 : 8
                let start = index + 1
                let end = start + digitCount
                guard end <= bytes.count,
                      let scalarValue = UInt32(String(decoding: bytes[start..<end], as: UTF8.self), radix: 16),
                      let scalar = UnicodeScalar(scalarValue) else {
                    return nil
                }
                result.unicodeScalars.append(scalar)
                index = end - 1
            default:
                return nil
            }
            index += 1
            literalStart = index
        }
        return nil
    }

    private static func isBareTOMLKeyByte(_ byte: UInt8) -> Bool {
        (byte >= 65 && byte <= 90)
            || (byte >= 97 && byte <= 122)
            || (byte >= 48 && byte <= 57)
            || byte == 95
            || byte == 45
    }

    /// Removes a TOML comment without treating `#` inside quoted keys as a
    /// delimiter. This lets table headers retain trailing comments while the
    /// reconciliation scanner continues to preserve their original text.
    private static func tomlContentBeforeComment(in line: String) -> String {
        let bytes = Array(line.utf8)
        var quote: UInt8?
        var index = 0
        while index < bytes.count {
            if let activeQuote = quote {
                if bytes[index] == activeQuote,
                   activeQuote == literalQuote || !isEscaped(bytes, at: index) {
                    quote = nil
                }
            } else if bytes[index] == basicQuote || bytes[index] == literalQuote {
                quote = bytes[index]
            } else if bytes[index] == commentMarker {
                return String(decoding: bytes[..<index], as: UTF8.self)
            }
            index += 1
        }
        return line
    }

    private static func isCodexAdministrationTable(_ table: [String]) -> Bool {
        guard let namespace = table.first else { return false }
        return ["marketplaces", "plugins", "mcp_servers"].contains(namespace)
    }

}
